In [1]:
import numpy as np
import numpy.linalg as la

In [5]:
# generate a 2x2 matrix
A = np.matrix([[4,3],[5,2]])

# calculate the eigenvalues
eigenvals = la.eigvals(A)
eigval, eigvec = la.eig(A)

# Let's look at our results and then verify by hand
print("Original matrix:")
print(A)
print("\nJust the Eigen Values:")
print(eigenvals)
print("\nThe Eigen Decomposition:")
print("The Eigen Values:")
print(eigval)
print("The Eigen Vectors:")
print(eigvec)

Original matrix:
[[4 3]
 [5 2]]

Just the Eigen Values:
[ 7. -1.]

The Eigen Decomposition:
The Eigen Values:
[ 7. -1.]
The Eigen Vectors:
[[ 0.70710678 -0.51449576]
 [ 0.70710678  0.85749293]]


In [7]:
# for 3x3 matrix, the determinant is a little more complicated
# not so easy to calculate by hand... so a 4x4 is even more complicated

# generate the eigenvalues
A = np.matrix([[5,1,2,1],[2,1,4,3],[1,2,1,0],[1,2,2,1]])

# calculate the eigenvalues
eigenvals = la.eigvals(A)
print("Eigen Values:")
print(eigenvals)

Eigen Values:
[ 7.30033132  2.81646992  0.06681848 -2.18361972]
