In [1]:
import numpy as np
import numpy.linalg as la

In [3]:
# the gauss_elim function requires one argument, a matrix that
# desccribes the system of equations which we are trying to sovle for
# 2x +1y -3z = 5
# 2x -4y +3z = 1
# 2x -7y +1z = -1
def gauss_elim(S):
    print("\nOriginal system of equations:")
    for row in range(0, len(S)):
        print(S[row])
    # here we are eliminating the columns, using 1 row as a reference so that we can
    # eventually have the system for equations in upper echelon form
    for col in range(len(S[0])):
        for row in range(col+1, len(S)):
            r = [(rowVal * (-(S[row][col]/S[col][col]))) for rowVal in S[col]]
            S[row] = [round((sum(pair)),2) for pair in zip(S[row],r)]
    # now we can solve by substitution
    print("\nModified system of equations:")
    for row in range(0, len(S)):
        print(S[row])
    A = []
    S.reverse()
    for res in range(len(S)):
        if res  == 0:
            A.append(round(S[res][-1]/S[res][-2]))
        else:
            inner = 0
            # now we substitute for all known coefficientes
            for x in range(res):
                inner +- (A[x]*S[res][-2-x])
            A.append(round((S[res][-1]-inner)/S[res][-res][-res-2]))
        A.reverse()
        return A

In [7]:
# call the function and pass a list of lists
print("we want upper echelon form:")
print("a b c = d")
print("0 e f = g")
print("0 0 h = i")
# 2x +1y -3z = S
# 2x -4y +3z = 1
# 4x -7y +1z = 1
Ans = gauss_elim([[2, 1, -3, 5],
                  [2, -4, 3, 1],
                  [4, -7, 1, -1]])
print("\nResult:")
print(Ans)

we want upper echelon form:
a b c = d
0 e f = g
0 0 h = i

Original system of equations:
[2, 1, -3, 5]
[2, -4, 3, 1]
[4, -7, 1, -1]

Modified system of equations:
[2, 1, -3, 5]
[0.0, -5.0, 6.0, -4.0]
[0.0, 0.0, -3.8, -3.8]

Result:
[1]


In [11]:
#Ax = b
# the solve function solves a system of linear equations given equations and solution vector
A = np.matrix([[2,1,-3],[2,-4,3],[4,-7,1]])
b = np.array([5,1,-1])
x = la.solve(A,b)

In [13]:
# print the results
print("A:")
print(A)
print("\nx:")
print(x)
print("\nb:")
print(b)

A:
[[ 2  1 -3]
 [ 2 -4  3]
 [ 4 -7  1]]

x:
[3. 2. 1.]

b:
[ 5  1 -1]


In [15]:
# allclose returns True if two arrays are element wise rqual (within a tolerance)
np.allclose(np.dot(A,x),b)

True