In [1]:
import numpy as np
import numpy.linalg as la

In [7]:
# a pure rotation in R2 space gives an orthogonal matrix
# note that this is a square matrix
A = np.matrix([[00,-1],[1,0]])
print("Matrix A:")
print(A)
print("\nInverse of A:")
print(la.inv(A))
print("\nTranspose of A:")
print(A.T)

Matrix A:
[[ 0 -1]
 [ 1  0]]

Inverse of A:
[[ 0.  1.]
 [-1. -0.]]

Transpose of A:
[[ 0  1]
 [-1  0]]


In [9]:
# now because this is square orthonormal...
print("A*AT and AT*A:")
print(A*(A.T))
print((A.T)*A)
print("\nA*AInv and AInv*A:")
print(A*(la.inv(A)))
print((la.inv(A)*A))


A*AT and AT*A:
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]

A*AInv and AInv*A:
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [13]:
# use qr decomposition A + QR
A = np.matrix([[1,2],[3,4]])
Q, R = la.qr(A)
print("A:")
print(A)
print("\nNow use QR Decomposition")
print("Q:")
print(Q)
print("\nR:")
print(R)
print("\nQR gives original:")
print(Q*R)

A:
[[1 2]
 [3 4]]

Now use QR Decomposition
Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]

QR gives original:
[[1. 2.]
 [3. 4.]]


In [34]:
print("\nDot product of Q1 with Q1")
print(Q[0,0]*Q[0,0]+Q[1,0]*Q[1,0])
print("\nDot product of Q2 with Q2")
print(Q[0,1]*Q[0,1]+Q[1,1]*Q[1,1])
print("\nMagnitude of Q1")
print((Q[0,0]*Q[0,0]+Q[1,0]*Q[1,0])**.5)
print("\nMagnitude of Q2")
print((Q[0,1]*Q[0,1]+Q[1,1]*Q[1,1])**.5)


Dot product of Q1 with Q1
1.0

Dot product of Q2 with Q2
1.0

Magnitude of Q1
1.0

Magnitude of Q2
1.0
